### ISSUE TITLE
The Rudder axis overrides the Rz axis in the joystick driver.

### ISSUE THREAD

**Issue by GO63-samara** [jmriego/Fino#32] opened 2023-03-04 19:45 UTC
If both **Rz**-Axis and **Rudder**-Axis are specified, then **Rudder**-Axis overrides **Rz**-Axis in the joystick driver.
I propose to abandon the **Rz** axis, and use the **Slider** or **Dial** axis instead. These axes do not overlap with the Rudder axis and you can get a joystick with all eight axes working.

It is enough to fix one line in the **Joystick.cpp** file:

```
	if (includeRzAxis == true) {
		// USAGE (Rz)
		tempHidReportDescriptor[hidReportDescriptorSize++] = 0x09;
		//tempHidReportDescriptor[hidReportDescriptorSize++] = 0x35  // <-- delete this line
		tempHidReportDescriptor[hidReportDescriptorSize++] = 0x36;     //0x36 for Slider or 0x37 for Dial
	}

```

**Comment by jmriego** [comment] 2023-03-05 20:47
thanks for the report @GO63-samara .
I'd like to investigate a bit more about this before the change. I have been able to reproduce the issue in Windows but not in Linux, so it seems like it does not support a joystick with both an Rz and a rudder.

I have checked a MS FFB2 joystick and it seems like it has no rudder on the descriptor, but a Rz axis, so I think it would make more sense to change the rudder for a dial for example, but I want to investigate a bit more on what's the most typical axis found and what would be better supported.

This really seems like a Windows driver bug more than an issue with the code here, but as I guess most people would try to use this with Windows it makes sense to remove an axis that it's not that well supported

**Comment by GO63-samara** [comment] 2023-03-05 22:54
You can also try conditional compilation:
If both Rz and Rudder axes are used, then replace the Rz axis with the Slider axis or with the Dial axis, with a compiler warning.
If only one axis Rz or Rudder is used, then do not change anything, and it works so well.

**Comment by GO63-samara** [comment] 2023-03-06 14:39
Maybe do so?

```
	if (includeRzAxis == true) {
		// USAGE (Rz)
		tempHidReportDescriptor[hidReportDescriptorSize++] = 0x09;
		if (includeRudder) tempHidReportDescriptor[hidReportDescriptorSize++] = 0x37; //Dial instead of Rz
		else tempHidReportDescriptor[hidReportDescriptorSize++] = 0x35;
	}

```
I have verified that this code works correctly in all four combinations of includeRzAxis and includeRudder.
If both includeRzAxis and includeRudder are defined, then Rz-Axis is changed to Dial-axis.

**Comment by jmriego** [comment] 2023-03-07 16:48
I'd definitely prefer to keep the Rz axis untouched as that has the best support I've seen between the dials, sliders, rudders, etc.

After checking Joystick Gremlin, x360ce, DCS world, FreePie and others it looks to me like the best solution is to remove the rudder and throttle, and instead add a slider. All of these work correctly with a Rz axis but some of these don't support rudder and/or throttle. That would also be more aligned with what commercial joysticks usually report so should be better for game support.

It should probably include a Slider and maybe also a Dial. That still gives you 8 axis for a device

**Comment by GO63-samara** [comment] 2023-03-07 19:09
In general, these overlays occur when using Axis and Simulation Control at the same time.
If you leave only Axis, and remove Simulation Control, then everything works correctly.

Do what you think is right. The main thing is that 8 axes should work simultaneously in Windows.

**Comment by jmriego** [comment] 2023-03-07 21:09
sorry, I might be feeling think now hehehe but what do you mean about Axis and Simulation Control?

**Comment by GO63-samara** [comment] 2023-03-07 21:16
Well, I didn't express myself exactly. I mean the axes from the `USAGE page (Pointer)`
and axes from `USAGE_PAGE (Simulation Controls)`

**Comment by GO63-samara** [comment] 2023-03-08 13:06
Same problem with 8 axes is solved by @Hyratel here:
https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/221

and here:
https://github.com/Hyratel/ArduinoJoystickWithFFBLibrary/blob/master/src/JoystickFFBXA.cpp

`Slider`-axis and `Dial`-zxis are used instead of `Rudder`-axis and `Throttle`-axis. The `USAGE_PAGE (Simulation Controls)` page has been completely removed.

In my opinion, this is a good decision.

**Comment by jmriego** [comment] 2023-03-08 17:21
I completely agree with the solution mentioned by @Hyratel there. Those are the some axes I proposed so no problem there. I also found that Windows calibration dialog doesn't show all the axes so we cannot use that to decide what to include, but I would prefer to include things that are going to be working in practice (I mean, that would work in DCS, Joystick Gremlin, IL-2 or some other tools I'll use for testing).

Thanks for the comments about the DEG_TO_RAD and about no longer needing that usage page. I'll work on this and add it to the repo

**Comment by jmriego** [comment] 2023-03-09 20:12
I just created #34 to make this change. I'll be testing it properly but feel free to start playing with it

**Comment by GO63-samara** [comment] 2023-03-10 19:27
I checked it works really well!

In the `rotation_axes` branch https://github.com/jmriego/Fino/commit/648a54c90f20b352542790a72227fd99ae961224 , Rudder-axis overrides Rz-axis. As a result, we get no more than 7 working axes in the joystick.
In the `dial` branch https://github.com/jmriego/Fino/commit/b96a2e82e4e3df6798889a4b6266dee11b6253a5 , all 8 axes work correctly.

For a joystick with 7 or 8 axes, 72 or 70 bytes are saved in PROGMEM, due to the complete elimination of the `USAGE_PAGE (Simulation Controls`) page.

Good job!

**Comment by GO63-samara** [comment] 2023-03-10 19:31
And in the thirteenth commit, a small fly in the ointment :smile:  (Offtopic again).
There is still a warning

`src/Joystick.h:59:0: warning: "DEG_TO_RAD" redefined
`

I would remove this extra line, or suppress the warning:
```
#undef  DEG_TO_RAD
#define DEG_TO_RAD ((float)((float)3.14159265359 / 180.0))
```

**Comment by Hyratel** [comment] 2023-03-10 20:06
this page explains much about why this all happens: https://learn.microsoft.com/en-us/windows-hardware/drivers/hid/axis-selection

in short: if using Directinput API (which most will, unless you have reason to read the Raw HID), any Sim Axes will override a specific Generic Axis, (though it appears there's a typo: that page describes GENERIC_DIAL to GUID_Slider, in collision with GENERIC_SLIDER - this does not Make Sense, nor match Shown Behavior)

**Comment by jmriego** [comment] 2023-03-12 19:29
thanks a lot @Hyratel ! that's great info to understand the reasons and it now makes sense why this was working this way.

It's not completely related, but do you know about how are usually wheels reported? I understand from this page that most of them would use Y, Z and Rz so there should not be any need to support simulation axes for creating FFB driving wheels using this repo, right?

**Comment by Hyratel** [comment] 2023-03-13 22:34
`Generic_Wheel` is a Scroll Wheel/Encoder, not Steering. 
Steering -> DI_X
Gas -> DI_Y
Brake -> DI_RZ

but these are all *extremely arbitrary* if your Sim/Game allows for axis mapping. you can have a RaceWheel generically report as a gamepad or joystick with X/Y/Z if you wanted and knew you could Map it

the axis letter is just an Easy Name for "Axis #1" "Axis #2" etc. the letters in X=1 Y=2 etc are just a convenience-convention

**Comment by jmriego** [comment] 2023-03-14 17:37
oh ok, in that case I need to review that a bit. I'm going to close this issue as we already have made it so that this supports 8 axes but will start reviewing any other changes we might want to do in the future. Thanks again!

**Closed by jmriego** 2023-03-14 17:37 UTC
