### ISSUE TITLE
steering wheel support

### ISSUE THREAD

**Issue by f2knpw** [jmriego/Fino#15] opened 2021-06-05 11:08 UTC
Thanks a lot for this ffb joystick implementation.
I am looking for a steering wheel ffb driver to try to make a wheel with an hoverboard BLDC motor.
I don't know if your firmware could handle wheels ?
Regards
JP

**Comment by jmriego** [comment] 2021-06-05 13:15
no worries! yes, this should work with steering wheels but it would appear as a normal joystick to games because of some changes I made. It should be fine for most games though.
Anyway, I'm going to make changes to the library to add that support this weekend and will be closing this ticket because it's actually a duplicate of #11

**Closed by jmriego** 2021-06-05 13:15 UTC

**Comment by f2knpw** [comment] 2021-06-05 13:31
thanks so much
